In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [2]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7])

is_float64 = arr.dtype == np.float64

print(is_float64)

True


In [3]:
import numpy as np

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [4]:
import numpy as np

arr = np.array([1.23456789, 2.3456789, 3.456789], dtype=np.float64)

# Convert to float32
arr_float32 = arr.astype(np.float32)

print(arr)
print(arr_float32)

[1.23456789 2.3456789  3.456789  ]
[1.2345679 2.3456788 3.456789 ]


In [ ]:
 4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [5]:
import numpy as np



arr = np.array([1, 2, 3, 4])  # Example integer array

arr_float32 = arr.astype(np.float32)  



print(arr_float32)  

# Output: [1. 2. 3. 4.]


[1. 2. 3. 4.]


In [ ]:
 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type 


In [13]:
import numpy as npy

# creating a 2-d array
arr1 = npy.array([[1, 3, 5, 7], [2, 4, 6, 8]])

# creating a 3-d array
arr2 = npy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr1.dtype) 

(2, 4)
(2, 2, 2)
8
int64


In [ ]:
7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [15]:
arr_1d = np.array([1, 2, 3])  # 1-dimensional array
arr_2d = np.array([[1, 2], [3, 4]])  # 2-dimensional array 

print((arr_1d)) 
print((arr_2d))  

[1 2 3]
[[1 2]
 [3 4]]


In [ ]:
 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.



In [16]:
# import library
import numpy as np

# create numpy 1d-array
x = np.array([100, 20, 34])

print("Memory size of a NumPy array:",
	x.nbytes)


Memory size of a NumPy array: 24


In [ ]:
 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


In [20]:
arr = np.array([[8, 2, 3], [7, 5, 6]])

print(arr.strides) 

(24, 8)


In [ ]:
 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.



In [21]:
 
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}")
print(f"Strides: {strides}")

NameError: name 'shape_stride_relationship' is not defined

In [ ]:
 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.



In [23]:
import numpy as np

# Create a 3x3 array of zeros
zero_array = np.zeros((3, 3))
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.



In [25]:
import numpy as np

array = np.ones(5)
print(array) 


[1. 1. 1. 1. 1.]


In [ ]:
 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 



In [3]:
import numpy as np

start = 0
step = 1.25
num = 9

result = start + np.arange(0, num) * step

In [ ]:
 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.



In [4]:
import numpy as np

# Creating a 2*2 identity matrix
identity_matrix = np.eye(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


In [ ]:
 16. Write a function that takes a Python list and converts it into a NumPy array.


In [5]:
import numpy as np

a = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
arr = np.array(a)

print(arr)

[1 2 3 4 5]


In [ ]:
 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data


In [8]:
import numpy as np


# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:")
print(arr)
print("Original array id:")
print(id(arr))

# Create a view of the array
arr_view = arr.view()
print("\nView of the array:")
print(arr_view)
print("View array id:")
print(id(arr_view))

# Modify the view
arr_view[0] = 10
print("\nModified view:")
print(arr_view)

# The original array is also modified
print("Original array after modifying the view:")
print(arr)

Original array:
[1 2 3 4 5]
Original array id:
2344825860432

View of the array:
[1 2 3 4 5]
View array id:
2344825860336

Modified view:
[10  2  3  4  5]
Original array after modifying the view:
[10  2  3  4  5]


In [ ]:
 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.



In [1]:
# Program to concatenate two 2D arrays row-wise
import numpy as np

# Creating two 2D arrays
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)

# axis = 0 implies that it is being done row-wise
np.concatenate((arr1, arr2), axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
 20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [2]:
import numpy as np

# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
print(c)


[[1 2 3]
 [4 5 6]]


In [ ]:
 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.



In [3]:
import numpy as np 

#create an array 
arr= np.arange(5 , 10)
print(arr)


[5 6 7 8 9]


In [ ]:
 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).



In [4]:
import numpy as np

# Generate 10 numbers between 0 and 1
array = np.linspace(0, 1, num=10)
print(array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000



In [14]:
import numpy as np

# Function to create logarithmically spaced values
def log_spaced_array(start, stop, num_values):
    return np.logspace(np.log10(start), np.log10(stop), num=num_values)

# Create an array of 5 logarithmically spaced values between 1 and 1000
log_array = log_spaced_array(1, 1000, 5)

# Print the result
print(log_array)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.



In [15]:
import numpy as np
import pandas as pd

# Step 1: Create a NumPy array with 5 rows and 3 columns, random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Step 2: Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Step 3: Print the DataFrame
print(df)


   Column1  Column2  Column3
0       77       71       83
1       50        2       87
2       98       93        8
3       57       88        8
4       88       59       84


In [5]:
# importing pandas and numpy libraries
import numpy as np
import pandas as pd

data = np.random.randint(5, 35, size=11)
df = pd.DataFrame(data, columns=['random_numbers'])

# displaying random integers in data frame
print(df)


    random_numbers
0               26
1               20
2                8
3               15
4               33
5               34
6               12
7               33
8               23
9               19
10              24


In [ ]:
 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 


In [16]:
import pandas as pd

# Function to replace negative values in a specific column
def replace_negative_values(df, column_name, replacement_value=0):
    # Replace negative values in the specified column
    df[column_name] = df[column_name].apply(lambda x: replacement_value if x < 0 else x)
    return df

# Example DataFrame
data = {'A': [10, -5, 3, -1, 8],
        'B': [-2, 7, -6, 4, 0],
        'C': [3, 2, -1, 4, -3]}

df = pd.DataFrame(data)

# Replace negative values in column 'A' with 0
modified_df = replace_negative_values(df, 'A', 0)

# Print the modified DataFrame
print(modified_df)


    A  B  C
0  10 -2  3
1   0  7  2
2   3 -6 -1
3   0  4  4
4   8  0 -3


In [ ]:
 26. Access the 3rd element from the given NumPy array.
 arr = np.array([10, 20, 30, 40, 50])


In [17]:
import numpy as np

# Create a 1D NumPy array with five elements
arr = np.array([10, 20, 30, 40, 50])


print(arr[3]) 


40


In [ ]:
 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
 arr_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                      [7, 8, 9]])




In [1]:

                    import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2]) 

6


In [ ]:
 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 arr = np.array([3, 8, 2, 10, 5, 7])


In [2]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask for elements greater than 5
mask = arr > 5

# Use the mask to extract the elements
result = arr[mask]

print(result)

[ 8 10  7]


In [ ]:
 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
 import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print(sliced_array)

[3 4 5 6]


In [ ]:
30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


In [4]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [ ]:
31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
provided in another array.


In [ ]:
 Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing.
 

In [5]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension

In [17]:
import numpy as np

# Function to extract elements using indices from three separate arrays
def extract_elements_from_3d_array(arr, x_indices, y_indices, z_indices):
    # Use advanced indexing to extract elements based on the indices
    return arr[x_indices, y_indices, z_indices]

# Example 3D array (shape: 3x3x3)
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

# Indices for each dimension
x_indices = np.array([0, 1, 2])
y_indices = np.array([0, 1, 2])
z_indices = np.array([2, 1, 0])

# Extract elements using the function
extracted_elements = extract_elements_from_3d_array(arr, x_indices, y_indices, z_indices)

# Print the extracted elements
print("Extracted elements:", extracted_elements)


Extracted elements: [ 3 14 25]


In [ ]:
 34 Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
35.create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays

In [18]:
import numpy as np

# Function to extract elements from a 2D array using row and column indices
def extract_elements_from_2d_array(arr, row_indices, col_indices):
    # Use advanced indexing to extract elements
    return arr[row_indices, col_indices]

# Example 2D array (shape: 4x4)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# Row and column indices
row_indices = np.array([0, 2, 3])
col_indices = np.array([1, 3, 0])

# Extract elements using the function
extracted_elements = extract_elements_from_2d_array(arr, row_indices, col_indices)

# Print the extracted elements
print("Extracted elements:", extracted_elements)


Extracted elements: [ 2 12 13]


In [ ]:
 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [8]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
scalar = 10  # Scalar value

result = array_2d + scalar
print(result)


[[11 12 13]
 [14 15 16]]


In [ ]:
 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting

In [9]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)


[[10 40]
 [30 80]]


In [ ]:
 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.



In [1]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape: (1, 4)
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])  # Shape: (4, 3)

# Add arr1 to each row of arr2 using broadcasting
result = arr1 + arr2

# Print the result
print(result)

ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

In [ ]:
 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.



In [2]:
import numpy as np

# Create the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([4, 5, 6])  # Shape (1, 3) or np.array([[4, 5, 6]])

# Add the arrays using broadcasting
result = arr1 + arr2

# Print the result
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
40. given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility

In [19]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

# Step 1: Reshape arr2 to (2, 3) to match the shape of arr1 (broadcasting it)
arr2_reshaped = arr2[:, :3]  # Take the first 3 columns (if possible)

# Step 2: Perform element-wise multiplication
result = arr1 * arr2_reshaped

# Print results
print("arr1:\n", arr1)
print("arr2 reshaped:\n", arr2_reshaped)
print("Multiplication result:\n", result)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
 41. Calculate column-wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Column-wise mean
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


In [ ]:
Find maximum value in each row of the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Maximum value in each row
row_max = np.max(arr, axis=1)
print(row_max)


[3 6]


In [ ]:
43.For the given array, find indices of maximum value in each column.
 arr = np.array([[1, 2, 3], [4, 5, 6]])
 

In [5]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find indices of maximum values in each column
max_indices = np.argmax(arr, axis=0)
print(max_indices)


[1 1 1]


In [ ]:
44.for the given array, apply custom function to calculate moving sum along rows.
 arr = np.array([[1, 2, 3], [4, 5, 6]])
 

In [6]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Custom function to calculate moving sum along rows
def moving_sum(row, window_size):
    return np.array([np.sum(row[i:i+window_size]) for i in range(len(row) - window_size + 1)])

# Apply the function to each row with a window size of 2
window_size = 2
moving_sums = np.apply_along_axis(moving_sum, axis=1, arr=arr, window_size=window_size)

print(moving_sums)


[[ 3  5]
 [ 9 11]]


In [ ]:
45. In the given array, check if all elements in each column are even
 arr = np.array([[2, 4, 6], [3, 5, 7]])

In [7]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
even_check = np.all(arr % 2 == 0, axis=0)

print(even_check)


[False False False]


In [ ]:
46.given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns.  Return the 
reshaped matrix.
 original_array = np.array([1, 2, 3, 4, 5, 6])
 

In [1]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3  # example dimensions (2 rows, 3 columns)

if original_array.size != m * n:
    raise ValueError("The total size of the new matrix must match the original array.")

reshaped_matrix = original_array.reshape((m, n))
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [ ]:
47.create a function that takes a matrix as input and returns the flattened array.
 input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [2]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

# Example usage:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [ ]:
48.Write a function that concatenates two given arrays along a specified axis.
 array1 = np.array([[1, 2], [3, 4]])
 array2 = np.array([[5, 6], [7, 8]])
 

In [3]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concat_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concat_axis0)

# Concatenate along axis 1 (columns)
concat_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concat_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
Create a function that splits an array into multiple sub-arrays along a specified axis.
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
import numpy as np

def split_array(array, indices_or_sections, axis=0):
    
    
    return np.split(array, indices_or_sections, axis=axis)

# Example usage:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split into 3 equal parts along axis 0 (rows)
split_rows = split_array(original_array, 3, axis=0)
print("Split along axis 0:")
for sub_array in split_rows:
    print(sub_array)

# Split into 3 equal parts along axis 1 (columns)
split_cols = split_array(original_array, 3, axis=1)
print("\nSplit along axis 1:")
for sub_array in split_cols:
    print(sub_array)


Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [ ]:
Write a function that inserts and then deletes elements from a given array at specified indices.
 original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3]


In [5]:
import numpy as np

def insert_and_delete(array, insert_indices, insert_values, delete_indices):
    # Insert values at the specified indices
    modified_array = np.insert(array, insert_indices, insert_values)
    
    # Delete elements at the specified indices (adjusted if needed)
    modified_array = np.delete(modified_array, delete_indices)
    
    return modified_array

# Example usage:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array:", result)


Resulting array: [ 1 10  4 11  5]


In [ ]:
 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.

In [1]:
import numpy as np

# Create arr1 with random integers between 0 and 10 (size 10)
arr1 = np.random.randint(0, 11, size=10)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition
result = arr1 + arr2

# Display the arrays and result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition result:", result)


arr1: [ 1  1 10  1  6  0  8  9  6  5]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition result: [ 2  3 13  5 11  6 15 17 15 15]


In [ ]:
52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise

In [2]:
import numpy as np

# Create arr1 with integers from 10 to 1 (descending)
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10 (ascending)
arr2 = np.arange(1, 11)

# Perform element-wise subtraction: arr1 - arr2
result = arr1 - arr2

# Display the arrays and result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`.

In [3]:
import numpy as np

# Create arr1 with random integers between 0 and 10, size 5
arr1 = np.random.randint(0, 11, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

# Display the arrays and result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)


arr1: [9 4 5 7 7]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 9  8 15 28 35]


In [ ]:
 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`

In [4]:
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

# Display the arrays and result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [ ]:
55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [5]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation
result = arr1 ** arr2

# Display the arrays and result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation result:", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


In [ ]:
 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [6]:
import numpy as np

def count_substring(arr, substring):
    # Use list comprehension with str.count to count occurrences in each string
    return sum([s.count(substring) for s in arr])

# Sample array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Example usage
substring = 'lo'
count = count_substring(arr, substring)

print(f"The substring '{substring}' appears {count} times.")


The substring 'lo' appears 3 times.


In [ ]:
 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']

In [7]:
import numpy as np

def extract_uppercase(arr):
    # Extract uppercase characters from each string
    return [''.join([char for char in s if char.isupper()]) for s in arr]

# Sample array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Call the function
uppercase_chars = extract_uppercase(arr)

print("Uppercase characters from each string:", uppercase_chars)


Uppercase characters from each string: ['H', 'W', 'OAI', 'GPT']


In [ ]:
58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [8]:
import numpy as np

def replace_substring(arr, old, new):
    # Use vectorized np.char.replace for efficiency
    return np.char.replace(arr, old, new)

# Sample array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace 'apple' with 'orange'
result = replace_substring(arr, 'apple', 'orange')

print("Modified array:", result)


Modified array: ['orange' 'banana' 'grape' 'pineorange']


In [ ]:
 59. Write a function that concatenates strings in a NumPy array element-wise.
 arr1 = np.array(['Hello', 'World'])

 arr2 = np.array(['Open', 'AI'])
 

In [10]:
import numpy as np

def concatenate_elementwise(arr1, arr2):
    # Use np.char.add for element-wise string concatenation
    return np.char.add(arr1, arr2)

# Sample arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Call the function
result = concatenate_elementwise(arr1, arr2)

print("Concatenated array:", result)


Concatenatesd array: ['HelloOpen' 'WorldAI']


In [ ]:
 60. Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [11]:
import numpy as np

def longest_string_length(arr):
    # Use np.char.str_len to get the length of each string and return the maximum length
    return np.max(np.char.str_len(arr))

# Sample array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Call the function
longest_length = longest_string_length(arr)

print("Length of the longest string:", longest_length)


Length of the longest string: 9


In [ ]:
  61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions

In [12]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

# Display the results
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")


Mean: 469.09
Median: 489.0
Variance: 83635.8819
Standard Deviation: 289.1986893123826


In [ ]:
 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset

In [13]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Display the results
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 29.75
75th Percentile: 71.75


In [ ]:
 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function.
 

In [1]:
import numpy as np

# Create two arrays (variables)
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(x, y)

print("Correlation coefficient matrix:")
print(correlation_matrix)

# To get just the correlation coefficient between x and y
correlation_coefficient = correlation_matrix[0, 1]
print("Correlation coefficient between x and y:", correlation_coefficient)


Correlation coefficient matrix:
[[1. 1.]
 [1. 1.]]
Correlation coefficient between x and y: 0.9999999999999999


In [ ]:
 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [2]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Perform matrix multiplication using dot()
result = np.dot(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResult of A dot B:")
print(result)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of A dot B:
[[19 22]
 [43 50]]


In [ ]:
 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.

In [3]:
import numpy as np

# Create an array of 50 random integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate percentiles and quartiles
percentile_10 = np.percentile(data, 10)
median = np.percentile(data, 50)  # or np.median(data)
percentile_90 = np.percentile(data, 90)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

# Print results
print("Data array:\n", data)
print(f"\n10th percentile: {percentile_10}")
print(f"Median (50th percentile): {median}")
print(f"90th percentile: {percentile_90}")
print(f"First quartile (Q1 - 25th percentile): {q1}")
print(f"Third quartile (Q3 - 75th percentile): {q3}")


Data array:
 [489 114 659 721 241 467 274 201 544 331 372 804 981  89  71 290 814 586
 684 226 443 164 526 599  13 716 542 132 404  60 500  84 428 630 467 825
 755 384 592 196 154 319 313 973 770 888 533 963 680 545]

10th percentile: 111.50000000000001
Median (50th percentile): 478.0
90th percentile: 815.1
First quartile (Q1 - 25th percentile): 249.25
Third quartile (Q3 - 75th percentile): 674.75


In [ ]:
 Create a NumPy array of integers and find the index of a specific element.

In [4]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60])

# Define the element to find
element_to_find = 40

# Find the index of the element
index = np.where(arr == element_to_find)

print("Array:", arr)
print(f"Index of element {element_to_find}:", index[0][0])


Array: [10 20 30 40 50 60]
Index of element 40: 3


In [ ]:
67. Generate a random NumPy array and sort it in ascending order

In [5]:
import numpy as np

# Generate a random NumPy array of 10 integers between 1 and 100
random_array = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original array:", random_array)
print("Sorted array (ascending):", sorted_array)


Original array: [73 81 35 64 30 86 39 86 92  3]
Sorted array (ascending): [ 3 30 35 39 64 73 81 86 86 92]


In [ ]:
 68. Filter elements >20  in the given NumPy array.
 arr = np.array([12, 25, 6, 42, 8, 30])

In [6]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered = arr[arr > 20]

print("Original array:", arr)
print("Filtered elements > 20:", filtered)


Original array: [12 25  6 42  8 30]
Filtered elements > 20: [25 42 30]


In [ ]:
 Filter elements which are divisible by 3 from a given NumPy array.
 arr = np.array([1, 5, 8, 12, 15]

In [7]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
div_by_3 = arr[arr % 3 == 0]

print("Original array:", arr)
print("Elements divisible by 3:", div_by_3)


Original array: [ 1  5  8 12 15]
Elements divisible by 3: [12 15]


In [ ]:
 70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
 arr = np.array([10, 20, 30, 40, 50]

In [1]:
import numpy as np

# Create the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print(filtered_arr)


[20 30 40]


In [ ]:
71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
 arr = np.array([1, 2, 3])

In [2]:
import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

print("Byte order:", byte_order)


Byte order: =


In [ ]:
 For the given NumPy array, perform byte swapping in place using `byteswap()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [3]:
import numpy as np

# Create the NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform in-place byte swapping
arr.byteswap(inplace=True)

# Display the modified array
print(arr)


[16777216 33554432 50331648]


In [ ]:
73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)
 

In [4]:
import numpy as np

# Create the NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Display the original and swapped arrays
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [ ]:
74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [5]:
import numpy as np
import sys

# Create the NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Determine the system's byte order
system_byteorder = sys.byteorder

# Swap the byte order only if the system's byte order is little-endian
if system_byteorder == 'little':
    swapped_arr = arr.newbyteorder('>')
else:
    swapped_arr = arr.newbyteorder('<')

# Display the original and swapped arrays
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [ ]:
75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`.
 arr = np.array([1, 2, 3], dtype=np.int32

In [2]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order of the array's dtype
byte_order = arr.dtype.byteorder

# Get the native byte order of the system
native_order = sys.byteorder  # 'little' or 'big'

# Determine if byte swapping is needed
if byte_order == '=':
    print("Byte order is native. No byte swapping needed.")
elif (byte_order == '<' and native_order == 'big') or (byte_order == '>' and native_order == 'little'):
    print("Byte swapping is necessary.")



Byte order is native. No byte swapping needed.


In [ ]:
76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [3]:
import numpy as np

# Step 1: Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Step 2: Create a copy of arr1
copy_arr = arr1.copy()

# Step 3: Modify an element in copy_arr
copy_arr[0] = 100

# Step 4: Print both arrays to check if arr1 is affected
print("arr1:", arr1)
print("copy_arr:", copy_arr)


arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [ ]:
77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [4]:
import numpy as np

# Step 1: Create a 3x3 matrix with random integers between 1 and 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Step 2: Extract a slice (e.g., first two rows and first two columns)
view_slice = matrix[:2, :2]

# Step 3: Modify an element in the slice
view_slice[0, 0] = 999

# Step 4: Print both arrays
print("Modified view_slice:\n", view_slice)
print("Original matrix:\n", matrix)


Modified view_slice:
 [[999   8]
 [  2   7]]
Original matrix:
 [[999   8  10]
 [  2   7   9]
 [  8   1   9]]


In [ ]:
78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

In [5]:
import numpy as np

# Step 1: Create array_a with values 1 to 12 reshaped to (4, 3)
array_a = np.arange(1, 13).reshape(4, 3)

# Step 2: Extract a slice (view), e.g., first two rows
view_b = array_a[:2, :]

# Step 3: Broadcast-add 5 to view_b (in-place)
view_b += 5  # This modifies the original array in-place

# Step 4: Print to check the effect
print("Modified view_b:\n", view_b)
print("Original array_a:\n", array_a)


Modified view_b:
 [[ 6  7  8]
 [ 9 10 11]]
Original array_a:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


In [7]:
#79
import numpy as np

# Step 1: Create orig_array with shape (2, 4) and values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Step 2: Create a reshaped view with shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Step 3: Modify an element in reshaped_view
reshaped_view[0, 0] = 999

# Step 4: Print both arrays to see if the change reflects in the original
print("reshaped_view:\n", reshaped_view)
print("orig_array:\n", orig_array)


reshaped_view:
 [[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]
orig_array:
 [[999   2   3   4]
 [  5   6   7   8]]


In [ ]:
80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data

In [8]:
import numpy as np

# Step 1: Create a 3x4 array with random integers between 1 and 10
data = np.random.randint(1, 11, size=(3, 4))

# Step 2: Extract elements greater than 5 and store as a copy
data_copy = data[data > 5].copy()

# Step 3: Modify an element in the copy
if data_copy.size > 0:
    data_copy[0] = 999

# Step 4: Print both arrays
print("Original data:\n", data)
print("Modified data_copy:\n", data_copy)


Original data:
 [[ 8  5  1  2]
 [10  6  5  5]
 [ 3  7  8  9]]
Modified data_copy:
 [999  10   6   7   8   9]


In [ ]:
81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them.


In [9]:
import numpy as np

# Step 1: Create two 3x3 matrices A and B with integer values
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Step 2: Perform addition and subtraction
add_result = A + B
sub_result = A - B

# Step 3: Print the results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition (A + B):\n", add_result)
print("Subtraction (A - B):\n", sub_result)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
82.Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [10]:
import numpy as np

# Step 1: Create matrix C (3x2)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Step 2: Create matrix D (2x4)
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Step 3: Perform matrix multiplication (C @ D)
result = C @ D  # or use np.matmul(C, D)

# Step 4: Print matrices and result
print("Matrix C (3x2):\n", C)
print("Matrix D (2x4):\n", D)
print("Matrix Multiplication Result (C @ D):\n", result)


Matrix C (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Matrix D (2x4):
 [[ 7  8  9 10]
 [11 12 13 14]]
Matrix Multiplication Result (C @ D):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [ ]:
83. Create a matrix `E` and find its transpose

In [11]:
import numpy as np

# Step 1: Create a matrix E (e.g., 3x2)
E = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Step 2: Find the transpose of E
E_transpose = E.T  # or np.transpose(E)

# Step 3: Print both matrices
print("Matrix E:\n", E)
print("Transpose of E:\n", E_transpose)


Matrix E:
 [[1 2]
 [3 4]
 [5 6]]
Transpose of E:
 [[1 3 5]
 [2 4 6]]


In [ ]:
84. Generate a square matrix `F` and compute its determinant

In [12]:
import numpy as np

# Step 1: Create a square matrix F (e.g., 3x3)
F = np.array([[2, 5, 3],
              [1, -2, -1],
              [1, 3, 4]])

# Step 2: Compute the determinant
det_F = np.linalg.det(F)

# Step 3: Print the matrix and its determinant
print("Matrix F:\n", F)
print("Determinant of F:", det_F)


Matrix F:
 [[ 2  5  3]
 [ 1 -2 -1]
 [ 1  3  4]]
Determinant of F: -20.000000000000007


In [ ]:
 85. Create a square matrix `G` and find its inverse

In [13]:
import numpy as np

# Step 1: Create a square matrix G (e.g., 2x2 or 3x3)
G = np.array([[4, 7],
              [2, 6]])

# Step 2: Compute the inverse of G (if it exists)
try:
    G_inv = np.linalg.inv(G)
    print("Matrix G:\n", G)
    print("Inverse of G:\n", G_inv)
except np.linalg.LinAlgError:
    print("Matrix G is singular and does not have an inverse.")


Matrix G:
 [[4 7]
 [2 6]]
Inverse of G:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
